[window]
startup_mode="Maximized"
decorations="Transparent"
padding={x=5,y=30}
opacity=0.7
blur=true

# Preferred fonts: 
# BlexMono Nerd Font Propo, 
# Hack Nerd Font Propo, 
# JetBrainsMonoNL Nerd Font, 
# FiraMono Nerd Font Propo,
# CodeNewRoman Nerd Font Propo,
[font]
normal = { family = "CodeNewRoman Nerd Font Propo", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 18.0

[cursor]
style={ shape="Beam", blinking="Always" }
blink_interval=500


